"""Protocol contracts for repositories (Dependency Inversion).

Tools and routers depend on these protocols, not Motor implementations,
so tests can substitute fakes without monkey-patching.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from bson import ObjectId


@runtime_checkable
class IFacultyRepository(Protocol):
    async def text_search(self, query: str, limit: int = 5) -> list[dict[str, Any]]: ...
    async def regex_search(self, tokens: list[str], limit: int = 5) -> list[dict[str, Any]]: ...
    async def compound_name_search(self, name_tokens: list[str], limit: int = 5) -> list[dict[str, Any]]: ...
    async def find_by_expert_ids(self, expert_ids: list[str]) -> list[dict[str, Any]]: ...
    async def find_department(self, name: str) -> dict[str, Any] | None: ...
    async def find_faculty_by_department_id(self, dept_id: ObjectId) -> list[dict[str, Any]]: ...
    async def find_top_faculty_by_department(self, department_name: str, limit: int = 10) -> list[dict[str, Any]]: ...
    async def list_all_departments(self, category: str | None = None) -> list[dict[str, Any]]: ...
    async def find_faculty_by_expertise(self, expertise_terms: list[str], limit: int = 15) -> list[dict[str, Any]]: ...
    async def find_top_faculty_global(self, sort_by: str = "h_index", limit: int = 10, department_name: str | None = None) -> list[dict[str, Any]]: ...
    async def count_all_faculty(self, department_name: str | None = None) -> int: ...
    async def get_kerberos_to_faculty_map(self, kerberoses: list[str]) -> dict[str, dict[str, str]]: ...
    async def get_kerberos_to_dept_map(self) -> dict[str, str]: ...


@runtime_checkable
class IIpRepository(Protocol):
    async def get_by_application_number(self, application_number: str) -> dict[str, Any] | None: ...
    async def get_by_id(self, ip_id: str) -> dict[str, Any] | None: ...
    async def find_by_ids(self, ids: list[str]) -> list[dict[str, Any]]: ...
    async def search_by_title(self, title: str, limit: int = 5) -> list[dict[str, Any]]: ...
    async def find_by_inventor(self, kerberos: str | None = None, name: str | None = None, faculty_ref: str | ObjectId | None = None, limit: int = 200) -> list[dict[str, Any]]: ...
    async def count_documents(self, match: dict) -> int: ...
    async def aggregate(self, pipeline: list[dict], length: int = 500) -> list[dict[str, Any]]: ...
    async def resolve_department_names(self, dept_ids) -> dict[Any, str]: ...
    async def grouped_counts(self, match: dict, dimensions: list[str], limit: int = 300) -> list[dict[str, Any]]: ...


@runtime_checkable
class ITaxonomyRepository(Protocol):
    async def all_themes(self) -> list[dict[str, Any]]: ...
    async def all_domains(self) -> list[dict[str, Any]]: ...
    async def resolve_theme(self, term: str | None) -> dict[str, Any] | None: ...
    async def resolve_domain(self, term: str | None) -> dict[str, Any] | None: ...
    async def name_maps(self) -> tuple[dict[str, str], dict[str, str]]: ...
    async def theme_counts_for_department(self, department_id: Any) -> list[dict[str, Any]]: ...
    async def domain_counts(self, theme_id: Any, department_id: Any = None) -> list[dict[str, Any]]: ...
    async def config_counts(self, theme_id: Any = None, domain_id: Any = None, department_id: Any = None) -> dict[str, Any] | None: ...
    async def config_members(self, theme_id: Any = None, domain_id: Any = None, department_id: Any = None) -> dict[str, Any] | None: ...
    async def papers_in_context(self, theme_id: Any = None, domain_id: Any = None, department_ref: Any = None, kerberos: str | None = None, limit: int = 10, sort_by: str = "recency", year_from: int | None = None, year_to: int | None = None) -> tuple[list[dict[str, Any]], int]: ...
    async def theme_distribution(self, department_ref: Any = None, kerberos: str | None = None) -> list[dict[str, Any]]: ...
    async def domain_distribution(self, theme_id: Any = None, department_ref: Any = None, kerberos: str | None = None, limit: int = 100) -> list[dict[str, Any]]: ...
    async def count_in_context(self, theme_id: Any = None, domain_id: Any = None, department_ref: Any = None, kerberos: str | None = None) -> int: ...
    async def faculty_paper_counts(self, theme_id: Any = None, domain_id: Any = None, department_ref: Any = None, limit: int = 20) -> list[dict[str, Any]]: ...


@runtime_checkable
class IResearchRepository(Protocol):
    async def find_by_ids(self, ids: list[str], fields: dict | None = None) -> list[dict[str, Any]]: ...
    async def count_documents(self, match: dict) -> int: ...
    async def aggregate(self, pipeline: list[dict]) -> list[dict[str, Any]]: ...
    async def find_top_cited(self, match: dict, limit: int = 5) -> list[dict[str, Any]]: ...
    async def faculty_publication_stats(self, match: dict) -> dict[str, Any] | None: ...
    async def department_stats(self, match: dict) -> dict[str, Any]: ...
    async def global_stats(self, base_match: dict, dimension: str, sort_field: str, limit: int = 25) -> tuple[int, list[dict]]: ...
    async def trend_by_ids(self, paper_ids: list[str], year_from: int | None, year_to: int | None) -> list[dict]: ...
    async def kerberos_counts_for_ids(self, paper_ids: list[str], base_match: dict) -> list[dict[str, Any]]: ...
    async def papers_by_kerberos(self, base_match: dict) -> list[dict[str, Any]]: ...
