# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from embedding.v1 import embedding_pb2 as embedding_dot_v1_dot_embedding__pb2


class EmbeddingServiceStub(object):
    """East-west contract for the BGE embedding + cross-encoder reranker service.
    Served by opensearch/services/embedding; consumed by search-api and
    chatbot-agent through Envoy.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Embed = channel.unary_unary(
                '/embedding.v1.EmbeddingService/Embed',
                request_serializer=embedding_dot_v1_dot_embedding__pb2.EmbedRequest.SerializeToString,
                response_deserializer=embedding_dot_v1_dot_embedding__pb2.EmbedResponse.FromString,
                )
        self.Rerank = channel.unary_unary(
                '/embedding.v1.EmbeddingService/Rerank',
                request_serializer=embedding_dot_v1_dot_embedding__pb2.RerankRequest.SerializeToString,
                response_deserializer=embedding_dot_v1_dot_embedding__pb2.RerankResponse.FromString,
                )


class EmbeddingServiceServicer(object):
    """East-west contract for the BGE embedding + cross-encoder reranker service.
    Served by opensearch/services/embedding; consumed by search-api and
    chatbot-agent through Envoy.
    """

    def Embed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rerank(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=embedding_dot_v1_dot_embedding__pb2.EmbedRequest.FromString,
                    response_serializer=embedding_dot_v1_dot_embedding__pb2.EmbedResponse.SerializeToString,
            ),
            'Rerank': grpc.unary_unary_rpc_method_handler(
                    servicer.Rerank,
                    request_deserializer=embedding_dot_v1_dot_embedding__pb2.RerankRequest.FromString,
                    response_serializer=embedding_dot_v1_dot_embedding__pb2.RerankResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'embedding.v1.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """East-west contract for the BGE embedding + cross-encoder reranker service.
    Served by opensearch/services/embedding; consumed by search-api and
    chatbot-agent through Envoy.
    """

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/embedding.v1.EmbeddingService/Embed',
            embedding_dot_v1_dot_embedding__pb2.EmbedRequest.SerializeToString,
            embedding_dot_v1_dot_embedding__pb2.EmbedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Rerank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/embedding.v1.EmbeddingService/Rerank',
            embedding_dot_v1_dot_embedding__pb2.RerankRequest.SerializeToString,
            embedding_dot_v1_dot_embedding__pb2.RerankResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
