# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedding/v1/embedding.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x65mbedding/v1/embedding.proto\x12\x0c\x65mbedding.v1\"\x1d\n\x0c\x45mbedRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"\x1b\n\tEmbedding\x12\x0e\n\x06values\x18\x01 \x03(\x02\"`\n\rEmbedResponse\x12+\n\nembeddings\x18\x01 \x03(\x0b\x32\x17.embedding.v1.Embedding\x12\x0f\n\x07took_ms\x18\x02 \x01(\x01\x12\x11\n\tdimension\x18\x03 \x01(\x05\"@\n\rRerankRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x11\n\tdocuments\x18\x02 \x03(\t\x12\r\n\x05top_n\x18\x03 \x01(\x05\",\n\x0cRerankResult\x12\r\n\x05index\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x01\"N\n\x0eRerankResponse\x12+\n\x07results\x18\x01 \x03(\x0b\x32\x1a.embedding.v1.RerankResult\x12\x0f\n\x07took_ms\x18\x02 \x01(\x01\x32\x99\x01\n\x10\x45mbeddingService\x12@\n\x05\x45mbed\x12\x1a.embedding.v1.EmbedRequest\x1a\x1b.embedding.v1.EmbedResponse\x12\x43\n\x06Rerank\x12\x1b.embedding.v1.RerankRequest\x1a\x1c.embedding.v1.RerankResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding.v1.embedding_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMBEDREQUEST']._serialized_start=46
  _globals['_EMBEDREQUEST']._serialized_end=75
  _globals['_EMBEDDING']._serialized_start=77
  _globals['_EMBEDDING']._serialized_end=104
  _globals['_EMBEDRESPONSE']._serialized_start=106
  _globals['_EMBEDRESPONSE']._serialized_end=202
  _globals['_RERANKREQUEST']._serialized_start=204
  _globals['_RERANKREQUEST']._serialized_end=268
  _globals['_RERANKRESULT']._serialized_start=270
  _globals['_RERANKRESULT']._serialized_end=314
  _globals['_RERANKRESPONSE']._serialized_start=316
  _globals['_RERANKRESPONSE']._serialized_end=394
  _globals['_EMBEDDINGSERVICE']._serialized_start=397
  _globals['_EMBEDDINGSERVICE']._serialized_end=550
# @@protoc_insertion_point(module_scope)
