# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from chat.v1 import chat_pb2 as chat_dot_v1_dot_chat__pb2


class ChatServiceStub(object):
    """Internal helpers for the chatbot-agent. The public answer stream stays SSE
    at the api-gateway; this RPC exposes quota state to other services.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckQuota = channel.unary_unary(
                '/chat.v1.ChatService/CheckQuota',
                request_serializer=chat_dot_v1_dot_chat__pb2.CheckQuotaRequest.SerializeToString,
                response_deserializer=chat_dot_v1_dot_chat__pb2.CheckQuotaResponse.FromString,
                )


class ChatServiceServicer(object):
    """Internal helpers for the chatbot-agent. The public answer stream stays SSE
    at the api-gateway; this RPC exposes quota state to other services.
    """

    def CheckQuota(self, request, context):
        """Reads (does not consume) the per-user daily message quota.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckQuota,
                    request_deserializer=chat_dot_v1_dot_chat__pb2.CheckQuotaRequest.FromString,
                    response_serializer=chat_dot_v1_dot_chat__pb2.CheckQuotaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.v1.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Internal helpers for the chatbot-agent. The public answer stream stays SSE
    at the api-gateway; this RPC exposes quota state to other services.
    """

    @staticmethod
    def CheckQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.v1.ChatService/CheckQuota',
            chat_dot_v1_dot_chat__pb2.CheckQuotaRequest.SerializeToString,
            chat_dot_v1_dot_chat__pb2.CheckQuotaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
