# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat/v1/chat.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63hat/v1/chat.proto\x12\x07\x63hat.v1\"$\n\x11\x43heckQuotaRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"D\n\x12\x43heckQuotaResponse\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0c\n\x04used\x18\x02 \x01(\x05\x12\x11\n\tremaining\x18\x03 \x01(\x05\x32T\n\x0b\x43hatService\x12\x45\n\nCheckQuota\x12\x1a.chat.v1.CheckQuotaRequest\x1a\x1b.chat.v1.CheckQuotaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat.v1.chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHECKQUOTAREQUEST']._serialized_start=31
  _globals['_CHECKQUOTAREQUEST']._serialized_end=67
  _globals['_CHECKQUOTARESPONSE']._serialized_start=69
  _globals['_CHECKQUOTARESPONSE']._serialized_end=137
  _globals['_CHATSERVICE']._serialized_start=139
  _globals['_CHATSERVICE']._serialized_end=223
# @@protoc_insertion_point(module_scope)
