# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search/v1/search.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16search/v1/search.proto\x12\tsearch.v1\"H\n\x16\x46\x61\x63ultyForQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\t\x12\x11\n\tsearch_in\x18\x03 \x03(\t\"X\n\x07\x46\x61\x63ulty\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tauthor_id\x18\x02 \x01(\t\x12\x13\n\x0bpaper_count\x18\x03 \x01(\x05\x12\x17\n\x0frelevance_score\x18\x04 \x01(\x01\"Z\n\nDepartment\x12\x0c\n\x04name\x18\x01 \x01(\t\x12#\n\x07\x66\x61\x63ulty\x18\x02 \x03(\x0b\x32\x12.search.v1.Faculty\x12\x19\n\x11total_paper_count\x18\x03 \x01(\x05\"\x9f\x01\n\x17\x46\x61\x63ultyForQueryResponse\x12*\n\x0b\x64\x65partments\x18\x01 \x03(\x0b\x32\x15.search.v1.Department\x12\x15\n\rtotal_faculty\x18\x02 \x01(\x05\x12\x1d\n\x15total_matching_papers\x18\x03 \x01(\x05\x12\x0f\n\x07took_ms\x18\x04 \x01(\x01\x12\x11\n\tcache_hit\x18\x05 \x01(\x08\x32i\n\rSearchService\x12X\n\x0f\x46\x61\x63ultyForQuery\x12!.search.v1.FacultyForQueryRequest\x1a\".search.v1.FacultyForQueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search.v1.search_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FACULTYFORQUERYREQUEST']._serialized_start=37
  _globals['_FACULTYFORQUERYREQUEST']._serialized_end=109
  _globals['_FACULTY']._serialized_start=111
  _globals['_FACULTY']._serialized_end=199
  _globals['_DEPARTMENT']._serialized_start=201
  _globals['_DEPARTMENT']._serialized_end=291
  _globals['_FACULTYFORQUERYRESPONSE']._serialized_start=294
  _globals['_FACULTYFORQUERYRESPONSE']._serialized_end=453
  _globals['_SEARCHSERVICE']._serialized_start=455
  _globals['_SEARCHSERVICE']._serialized_end=560
# @@protoc_insertion_point(module_scope)
