# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from search.v1 import search_pb2 as search_dot_v1_dot_search__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in search/v1/search_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SearchServiceStub:
    """East-west contract for the Node/Fastify search-api (Docker service
    "search-api", gRPC listener on :50053, routed by Envoy on the /search.v1.
    prefix). It freezes the entire current /search/* surface, whose Fastify
    routes live under /api/v1 (public path = /search/api/v1/<route>).

    Two services share the one search-api gRPC listener (same package, same
    Envoy cluster + prefix):
    SearchService   -> search / author-scope / suggest / faculty-for-query /
    documents / author collaborators / ip/*
    TaxonomyService -> /api/v1/taxonomy/*

    Response-shape philosophy matches directory.v1: requests fully typed;
    deterministic payloads (suggest, taxonomy, faculty-for-query, collaborators)
    typed; document-bearing payloads returned as documented `*_json` strings
    because `results[]` are raw hydrated Mongo documents and facet `value`s are
    polymorphic (numeric years vs string ranges), which proto3 cannot round-trip
    faithfully. The gateway parses `*_json` and splices it verbatim so
    tech-ambit-explorer sees identical bodies. All /search endpoints are public
    (no auth) and read-only.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/search.v1.SearchService/Search',
                request_serializer=search_dot_v1_dot_search__pb2.SearchRequest.SerializeToString,
                response_deserializer=search_dot_v1_dot_search__pb2.SearchBodyResponse.FromString,
                _registered_method=True)
        self.SearchAuthorScope = channel.unary_unary(
                '/search.v1.SearchService/SearchAuthorScope',
                request_serializer=search_dot_v1_dot_search__pb2.AuthorScopeRequest.SerializeToString,
                response_deserializer=search_dot_v1_dot_search__pb2.SearchBodyResponse.FromString,
                _registered_method=True)
        self.Suggest = channel.unary_unary(
                '/search.v1.SearchService/Suggest',
                request_serializer=search_dot_v1_dot_search__pb2.SuggestRequest.SerializeToString,
                response_deserializer=search_dot_v1_dot_search__pb2.SuggestResponse.FromString,
                _registered_method=True)
        self.FacultyForQuery = channel.unary_unary(
                '/search.v1.SearchService/FacultyForQuery',
                request_serializer=search_dot_v1_dot_search__pb2.FacultyForQueryRequest.SerializeToString,
                response_deserializer=search_dot_v1_dot_search__pb2.FacultyForQueryResponse.FromString,
                _registered_method=True)
        self.GetDocument = channel.unary_unary(
                '/search.v1.SearchService/GetDocument',
                request_serializer=search_dot_v1_dot_search__pb2.GetDocumentRequest.SerializeToString,
                response_deserializer=search_dot_v1_dot_search__pb2.DocumentResponse.FromString,
                _registered_method=True)
        self.GetDocumentsByAuthor = channel.unary_unary(
                '/search.v1.SearchService/GetDocumentsByAuthor',
                request_serializer=search_dot_v1_dot_search__pb2.DocumentsByAuthorRequest.SerializeToString,
                response_deserializer=search_dot_v1_dot_search__pb2.DocumentsByAuthorResponse.FromString,
                _registered_method=True)
        self.GetSimilarDocuments = channel.unary_unary(
                '/search.v1.SearchService/GetSimilarDocuments',
                request_serializer=search_dot_v1_dot_search__pb2.SimilarDocumentsRequest.SerializeToString,
                response_deserializer=search_dot_v1_dot_search__pb2.SimilarDocumentsResponse.FromString,
                _registered_method=True)
        self.GetAuthorCollaborators = channel.unary_unary(
                '/search.v1.SearchService/GetAuthorCollaborators',
                request_serializer=search_dot_v1_dot_search__pb2.CollaboratorsRequest.SerializeToString,
                response_deserializer=search_dot_v1_dot_search__pb2.CollaboratorsResponse.FromString,
                _registered_method=True)
        self.IpSuggest = channel.unary_unary(
                '/search.v1.SearchService/IpSuggest',
                request_serializer=search_dot_v1_dot_search__pb2.SuggestRequest.SerializeToString,
                response_deserializer=search_dot_v1_dot_search__pb2.IpSuggestResponse.FromString,
                _registered_method=True)
        self.IpSearch = channel.unary_unary(
                '/search.v1.SearchService/IpSearch',
                request_serializer=search_dot_v1_dot_search__pb2.IpSearchRequest.SerializeToString,
                response_deserializer=search_dot_v1_dot_search__pb2.SearchBodyResponse.FromString,
                _registered_method=True)
        self.GetIpDocument = channel.unary_unary(
                '/search.v1.SearchService/GetIpDocument',
                request_serializer=search_dot_v1_dot_search__pb2.GetDocumentRequest.SerializeToString,
                response_deserializer=search_dot_v1_dot_search__pb2.DocumentResponse.FromString,
                _registered_method=True)


class SearchServiceServicer:
    """East-west contract for the Node/Fastify search-api (Docker service
    "search-api", gRPC listener on :50053, routed by Envoy on the /search.v1.
    prefix). It freezes the entire current /search/* surface, whose Fastify
    routes live under /api/v1 (public path = /search/api/v1/<route>).

    Two services share the one search-api gRPC listener (same package, same
    Envoy cluster + prefix):
    SearchService   -> search / author-scope / suggest / faculty-for-query /
    documents / author collaborators / ip/*
    TaxonomyService -> /api/v1/taxonomy/*

    Response-shape philosophy matches directory.v1: requests fully typed;
    deterministic payloads (suggest, taxonomy, faculty-for-query, collaborators)
    typed; document-bearing payloads returned as documented `*_json` strings
    because `results[]` are raw hydrated Mongo documents and facet `value`s are
    polymorphic (numeric years vs string ranges), which proto3 cannot round-trip
    faithfully. The gateway parses `*_json` and splices it verbatim so
    tech-ambit-explorer sees identical bodies. All /search endpoints are public
    (no auth) and read-only.

    """

    def Search(self, request, context):
        """POST /api/v1/search
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchAuthorScope(self, request, context):
        """POST /api/v1/search/author-scope
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Suggest(self, request, context):
        """GET /api/v1/suggest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FacultyForQuery(self, request, context):
        """GET /api/v1/search/faculty-for-query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocument(self, request, context):
        """GET /api/v1/document/:id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocumentsByAuthor(self, request, context):
        """GET /api/v1/documents/by-author/:authorId
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSimilarDocuments(self, request, context):
        """GET /api/v1/document/:id/similar
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthorCollaborators(self, request, context):
        """GET /api/v1/author/:id/collaborators
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IpSuggest(self, request, context):
        """GET /api/v1/ip/suggest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IpSearch(self, request, context):
        """POST /api/v1/ip/search
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIpDocument(self, request, context):
        """GET /api/v1/ip/document/:id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=search_dot_v1_dot_search__pb2.SearchRequest.FromString,
                    response_serializer=search_dot_v1_dot_search__pb2.SearchBodyResponse.SerializeToString,
            ),
            'SearchAuthorScope': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchAuthorScope,
                    request_deserializer=search_dot_v1_dot_search__pb2.AuthorScopeRequest.FromString,
                    response_serializer=search_dot_v1_dot_search__pb2.SearchBodyResponse.SerializeToString,
            ),
            'Suggest': grpc.unary_unary_rpc_method_handler(
                    servicer.Suggest,
                    request_deserializer=search_dot_v1_dot_search__pb2.SuggestRequest.FromString,
                    response_serializer=search_dot_v1_dot_search__pb2.SuggestResponse.SerializeToString,
            ),
            'FacultyForQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.FacultyForQuery,
                    request_deserializer=search_dot_v1_dot_search__pb2.FacultyForQueryRequest.FromString,
                    response_serializer=search_dot_v1_dot_search__pb2.FacultyForQueryResponse.SerializeToString,
            ),
            'GetDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocument,
                    request_deserializer=search_dot_v1_dot_search__pb2.GetDocumentRequest.FromString,
                    response_serializer=search_dot_v1_dot_search__pb2.DocumentResponse.SerializeToString,
            ),
            'GetDocumentsByAuthor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocumentsByAuthor,
                    request_deserializer=search_dot_v1_dot_search__pb2.DocumentsByAuthorRequest.FromString,
                    response_serializer=search_dot_v1_dot_search__pb2.DocumentsByAuthorResponse.SerializeToString,
            ),
            'GetSimilarDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSimilarDocuments,
                    request_deserializer=search_dot_v1_dot_search__pb2.SimilarDocumentsRequest.FromString,
                    response_serializer=search_dot_v1_dot_search__pb2.SimilarDocumentsResponse.SerializeToString,
            ),
            'GetAuthorCollaborators': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthorCollaborators,
                    request_deserializer=search_dot_v1_dot_search__pb2.CollaboratorsRequest.FromString,
                    response_serializer=search_dot_v1_dot_search__pb2.CollaboratorsResponse.SerializeToString,
            ),
            'IpSuggest': grpc.unary_unary_rpc_method_handler(
                    servicer.IpSuggest,
                    request_deserializer=search_dot_v1_dot_search__pb2.SuggestRequest.FromString,
                    response_serializer=search_dot_v1_dot_search__pb2.IpSuggestResponse.SerializeToString,
            ),
            'IpSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.IpSearch,
                    request_deserializer=search_dot_v1_dot_search__pb2.IpSearchRequest.FromString,
                    response_serializer=search_dot_v1_dot_search__pb2.SearchBodyResponse.SerializeToString,
            ),
            'GetIpDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIpDocument,
                    request_deserializer=search_dot_v1_dot_search__pb2.GetDocumentRequest.FromString,
                    response_serializer=search_dot_v1_dot_search__pb2.DocumentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'search.v1.SearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('search.v1.SearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SearchService:
    """East-west contract for the Node/Fastify search-api (Docker service
    "search-api", gRPC listener on :50053, routed by Envoy on the /search.v1.
    prefix). It freezes the entire current /search/* surface, whose Fastify
    routes live under /api/v1 (public path = /search/api/v1/<route>).

    Two services share the one search-api gRPC listener (same package, same
    Envoy cluster + prefix):
    SearchService   -> search / author-scope / suggest / faculty-for-query /
    documents / author collaborators / ip/*
    TaxonomyService -> /api/v1/taxonomy/*

    Response-shape philosophy matches directory.v1: requests fully typed;
    deterministic payloads (suggest, taxonomy, faculty-for-query, collaborators)
    typed; document-bearing payloads returned as documented `*_json` strings
    because `results[]` are raw hydrated Mongo documents and facet `value`s are
    polymorphic (numeric years vs string ranges), which proto3 cannot round-trip
    faithfully. The gateway parses `*_json` and splices it verbatim so
    tech-ambit-explorer sees identical bodies. All /search endpoints are public
    (no auth) and read-only.

    """

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.v1.SearchService/Search',
            search_dot_v1_dot_search__pb2.SearchRequest.SerializeToString,
            search_dot_v1_dot_search__pb2.SearchBodyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchAuthorScope(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.v1.SearchService/SearchAuthorScope',
            search_dot_v1_dot_search__pb2.AuthorScopeRequest.SerializeToString,
            search_dot_v1_dot_search__pb2.SearchBodyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Suggest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.v1.SearchService/Suggest',
            search_dot_v1_dot_search__pb2.SuggestRequest.SerializeToString,
            search_dot_v1_dot_search__pb2.SuggestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FacultyForQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.v1.SearchService/FacultyForQuery',
            search_dot_v1_dot_search__pb2.FacultyForQueryRequest.SerializeToString,
            search_dot_v1_dot_search__pb2.FacultyForQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.v1.SearchService/GetDocument',
            search_dot_v1_dot_search__pb2.GetDocumentRequest.SerializeToString,
            search_dot_v1_dot_search__pb2.DocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocumentsByAuthor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.v1.SearchService/GetDocumentsByAuthor',
            search_dot_v1_dot_search__pb2.DocumentsByAuthorRequest.SerializeToString,
            search_dot_v1_dot_search__pb2.DocumentsByAuthorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSimilarDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.v1.SearchService/GetSimilarDocuments',
            search_dot_v1_dot_search__pb2.SimilarDocumentsRequest.SerializeToString,
            search_dot_v1_dot_search__pb2.SimilarDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuthorCollaborators(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.v1.SearchService/GetAuthorCollaborators',
            search_dot_v1_dot_search__pb2.CollaboratorsRequest.SerializeToString,
            search_dot_v1_dot_search__pb2.CollaboratorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IpSuggest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.v1.SearchService/IpSuggest',
            search_dot_v1_dot_search__pb2.SuggestRequest.SerializeToString,
            search_dot_v1_dot_search__pb2.IpSuggestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IpSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.v1.SearchService/IpSearch',
            search_dot_v1_dot_search__pb2.IpSearchRequest.SerializeToString,
            search_dot_v1_dot_search__pb2.SearchBodyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIpDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.v1.SearchService/GetIpDocument',
            search_dot_v1_dot_search__pb2.GetDocumentRequest.SerializeToString,
            search_dot_v1_dot_search__pb2.DocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TaxonomyServiceStub:
    """--------------------------------------------------------------------------
    TaxonomyService  (/api/v1/taxonomy/*) — all reads, fully deterministic.
    --------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDepartments = channel.unary_unary(
                '/search.v1.TaxonomyService/GetDepartments',
                request_serializer=search_dot_v1_dot_search__pb2.EmptyRequest.SerializeToString,
                response_deserializer=search_dot_v1_dot_search__pb2.DepartmentsResponse.FromString,
                _registered_method=True)
        self.GetThemes = channel.unary_unary(
                '/search.v1.TaxonomyService/GetThemes',
                request_serializer=search_dot_v1_dot_search__pb2.ThemesRequest.SerializeToString,
                response_deserializer=search_dot_v1_dot_search__pb2.ThemesResponse.FromString,
                _registered_method=True)
        self.GetDomains = channel.unary_unary(
                '/search.v1.TaxonomyService/GetDomains',
                request_serializer=search_dot_v1_dot_search__pb2.DomainsRequest.SerializeToString,
                response_deserializer=search_dot_v1_dot_search__pb2.DomainsResponse.FromString,
                _registered_method=True)
        self.GetSubdomains = channel.unary_unary(
                '/search.v1.TaxonomyService/GetSubdomains',
                request_serializer=search_dot_v1_dot_search__pb2.SubdomainsRequest.SerializeToString,
                response_deserializer=search_dot_v1_dot_search__pb2.SubdomainsResponse.FromString,
                _registered_method=True)
        self.GetCounts = channel.unary_unary(
                '/search.v1.TaxonomyService/GetCounts',
                request_serializer=search_dot_v1_dot_search__pb2.CountsRequest.SerializeToString,
                response_deserializer=search_dot_v1_dot_search__pb2.CountsResponse.FromString,
                _registered_method=True)
        self.GetFaculty = channel.unary_unary(
                '/search.v1.TaxonomyService/GetFaculty',
                request_serializer=search_dot_v1_dot_search__pb2.TaxonomyFacultyRequest.SerializeToString,
                response_deserializer=search_dot_v1_dot_search__pb2.TaxonomyFacultyResponse.FromString,
                _registered_method=True)
        self.GetFacultyPapers = channel.unary_unary(
                '/search.v1.TaxonomyService/GetFacultyPapers',
                request_serializer=search_dot_v1_dot_search__pb2.TaxonomyFacultyPapersRequest.SerializeToString,
                response_deserializer=search_dot_v1_dot_search__pb2.TaxonomyFacultyPapersResponse.FromString,
                _registered_method=True)


class TaxonomyServiceServicer:
    """--------------------------------------------------------------------------
    TaxonomyService  (/api/v1/taxonomy/*) — all reads, fully deterministic.
    --------------------------------------------------------------------------
    """

    def GetDepartments(self, request, context):
        """GET /api/v1/taxonomy/departments
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetThemes(self, request, context):
        """GET /api/v1/taxonomy/themes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDomains(self, request, context):
        """GET /api/v1/taxonomy/domains
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubdomains(self, request, context):
        """GET /api/v1/taxonomy/domains/:domainSlug/subdomains
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCounts(self, request, context):
        """GET /api/v1/taxonomy/counts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFaculty(self, request, context):
        """GET /api/v1/taxonomy/faculty
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFacultyPapers(self, request, context):
        """GET /api/v1/taxonomy/faculty/:kerberos/papers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaxonomyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDepartments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDepartments,
                    request_deserializer=search_dot_v1_dot_search__pb2.EmptyRequest.FromString,
                    response_serializer=search_dot_v1_dot_search__pb2.DepartmentsResponse.SerializeToString,
            ),
            'GetThemes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetThemes,
                    request_deserializer=search_dot_v1_dot_search__pb2.ThemesRequest.FromString,
                    response_serializer=search_dot_v1_dot_search__pb2.ThemesResponse.SerializeToString,
            ),
            'GetDomains': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDomains,
                    request_deserializer=search_dot_v1_dot_search__pb2.DomainsRequest.FromString,
                    response_serializer=search_dot_v1_dot_search__pb2.DomainsResponse.SerializeToString,
            ),
            'GetSubdomains': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubdomains,
                    request_deserializer=search_dot_v1_dot_search__pb2.SubdomainsRequest.FromString,
                    response_serializer=search_dot_v1_dot_search__pb2.SubdomainsResponse.SerializeToString,
            ),
            'GetCounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCounts,
                    request_deserializer=search_dot_v1_dot_search__pb2.CountsRequest.FromString,
                    response_serializer=search_dot_v1_dot_search__pb2.CountsResponse.SerializeToString,
            ),
            'GetFaculty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFaculty,
                    request_deserializer=search_dot_v1_dot_search__pb2.TaxonomyFacultyRequest.FromString,
                    response_serializer=search_dot_v1_dot_search__pb2.TaxonomyFacultyResponse.SerializeToString,
            ),
            'GetFacultyPapers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFacultyPapers,
                    request_deserializer=search_dot_v1_dot_search__pb2.TaxonomyFacultyPapersRequest.FromString,
                    response_serializer=search_dot_v1_dot_search__pb2.TaxonomyFacultyPapersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'search.v1.TaxonomyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('search.v1.TaxonomyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaxonomyService:
    """--------------------------------------------------------------------------
    TaxonomyService  (/api/v1/taxonomy/*) — all reads, fully deterministic.
    --------------------------------------------------------------------------
    """

    @staticmethod
    def GetDepartments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.v1.TaxonomyService/GetDepartments',
            search_dot_v1_dot_search__pb2.EmptyRequest.SerializeToString,
            search_dot_v1_dot_search__pb2.DepartmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetThemes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.v1.TaxonomyService/GetThemes',
            search_dot_v1_dot_search__pb2.ThemesRequest.SerializeToString,
            search_dot_v1_dot_search__pb2.ThemesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDomains(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.v1.TaxonomyService/GetDomains',
            search_dot_v1_dot_search__pb2.DomainsRequest.SerializeToString,
            search_dot_v1_dot_search__pb2.DomainsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSubdomains(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.v1.TaxonomyService/GetSubdomains',
            search_dot_v1_dot_search__pb2.SubdomainsRequest.SerializeToString,
            search_dot_v1_dot_search__pb2.SubdomainsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.v1.TaxonomyService/GetCounts',
            search_dot_v1_dot_search__pb2.CountsRequest.SerializeToString,
            search_dot_v1_dot_search__pb2.CountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFaculty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.v1.TaxonomyService/GetFaculty',
            search_dot_v1_dot_search__pb2.TaxonomyFacultyRequest.SerializeToString,
            search_dot_v1_dot_search__pb2.TaxonomyFacultyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFacultyPapers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.v1.TaxonomyService/GetFacultyPapers',
            search_dot_v1_dot_search__pb2.TaxonomyFacultyPapersRequest.SerializeToString,
            search_dot_v1_dot_search__pb2.TaxonomyFacultyPapersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
