# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from search.v1 import search_pb2 as search_dot_v1_dot_search__pb2


class SearchServiceStub(object):
    """East-west contract for the Node search-api.
    Mirrors GET /api/v1/search/faculty-for-query (the aggregation used by the
    chatbot's find_faculty_for_topic tool and the People sidebar).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FacultyForQuery = channel.unary_unary(
                '/search.v1.SearchService/FacultyForQuery',
                request_serializer=search_dot_v1_dot_search__pb2.FacultyForQueryRequest.SerializeToString,
                response_deserializer=search_dot_v1_dot_search__pb2.FacultyForQueryResponse.FromString,
                )


class SearchServiceServicer(object):
    """East-west contract for the Node search-api.
    Mirrors GET /api/v1/search/faculty-for-query (the aggregation used by the
    chatbot's find_faculty_for_topic tool and the People sidebar).
    """

    def FacultyForQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FacultyForQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.FacultyForQuery,
                    request_deserializer=search_dot_v1_dot_search__pb2.FacultyForQueryRequest.FromString,
                    response_serializer=search_dot_v1_dot_search__pb2.FacultyForQueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'search.v1.SearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SearchService(object):
    """East-west contract for the Node search-api.
    Mirrors GET /api/v1/search/faculty-for-query (the aggregation used by the
    chatbot's find_faculty_for_topic tool and the People sidebar).
    """

    @staticmethod
    def FacultyForQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/search.v1.SearchService/FacultyForQuery',
            search_dot_v1_dot_search__pb2.FacultyForQueryRequest.SerializeToString,
            search_dot_v1_dot_search__pb2.FacultyForQueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
